[options]
addons_path = /mnt/enterprise,/mnt/extra-addons
publisher_warranty_url = https://ksujstlcvwunomyjpjjk.supabase.co/functions/v1/odoo-webhook
data_dir = /var/lib/odoo
admin_passwd = eduf-ei2v-rpwu


limit_time_cpu = 600
limit_time_real = 1200

# Indique à Odoo qu'il est derrière un proxy HTTPS
proxy_mode = True

# Active le multi-processing. Odoo va démarrer le trafic web sur le 8069 
# et allumer un serveur dédié aux websockets sur le 8072.
workers = 2